# Generated by Django 5.2.3 on 2025-06-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
