# Generated by Django 5.2.3 on 2025-06-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_noticia_autor_alter_noticia_cuerpo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_local', models.CharField(max_length=100)),
                ('escudo_local', models.ImageField(upload_to='escudos/')),
                ('equipo_visitante', models.CharField(max_length=100)),
                ('escudo_visitante', models.ImageField(upload_to='escudos/')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
