# Generated by Django 5.2.3 on 2025-06-14 02:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entradas', '0002_entrada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.RemoveField(
            model_name='entradapartido',
            name='comprador',
        ),
        migrations.RemoveField(
            model_name='entradapartido',
            name='fecha',
        ),
        migrations.AddField(
            model_name='entradapartido',
            name='fecha_partido',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradapartido',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='entradapartido',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='entradas'),
        ),
        migrations.AddField(
            model_name='tipoentrada',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_entrada', to='entradas.entradapartido'),
        ),
        migrations.AddField(
            model_name='compraentrada',
            name='tipo_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entradas.tipoentrada'),
        ),
    ]
